services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nav_directory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - nav_pg_data:/var/lib/postgresql/data

volumes:
  nav_pg_data:
